### ISSUE TITLE
TypeError: linspace(): argument 'steps' (position 3) must be int, not numpy.ndarray

### ISSUE THREAD

**Issue by prakashknaikade** [gkouros/refnerf-pytorch#4]
File "/HPS/ColorNeRF/work/refnerf-pytorch/internal/stepfun.py", line 203, in sample
    u = torch.linspace(0, 1. - eps, num_samples)
TypeError: linspace(): argument 'steps' (position 3) must be int, not numpy.ndarray

**Comment by 520jz** [comment]
> File "/HPS/ColorNeRF/work/refnerf-pytorch/internal/stepfun.py", line 203, in sample u = torch.linspace(0, 1. - eps, num_samples) TypeError: linspace(): argument 'steps' (position 3) must be int, not numpy.ndarray

Hello, I also had the same problem, do you know how to solve it

**Comment by prakashknaikade** [comment]
not really, sorry
